"""Pydantic models for the composing stage API."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from sdlicit.agents.transport import ClarificationItem, SocraticProbeOut
from sdlicit.helpers.artifact_naming import ArtifactMeta

__all__ = ["ClarificationItem", "SocraticProbeOut"]


# ---------------------------------------------------------------------------
# SOW creation (merged from intake_stage)
# ---------------------------------------------------------------------------


class CreateSOWRequest(BaseModel):
    """Raw project brief to convert into a structured SOW."""

    raw_brief: str = Field(..., description="Raw meeting notes or brain dump")
    clarifications: list[ClarificationItem] = Field(
        default_factory=list,
        description="Prior Socratic Q&A; sent back when resuming an interrupted call",
    )


class CreateSOWResponse(BaseModel):
    """Structured Statement of Work generated by the SOW agent."""

    sow_markdown: str = Field(
        default="", description="Generated SOW in Markdown format"
    )
    artifact_meta: ArtifactMeta | None = Field(
        default=None,
        description="Canonical filename and path — frontends must use this for saving",
    )
    socratic_probe: SocraticProbeOut | None = Field(
        default=None,
        description="If present, the CLI must answer the probe and re-call",
    )


class RegenerateSectionRequest(BaseModel):
    """Regenerate a single SOW section with user feedback."""

    raw_brief: str = Field(..., description="Original raw brief")
    section_name: str = Field(..., description="Section key to regenerate")
    prior_sections: str = Field(
        default="", description="Already-generated sections as markdown"
    )
    user_feedback: str = Field(default="", description="User's notes on what to change")
    current_content: str = Field(
        default="", description="Current section content being replaced"
    )
    clarifications: list[ClarificationItem] = Field(
        default_factory=list,
        description="Prior Socratic Q&A for this section — used to track turn count",
    )


class RegenerateSectionResponse(BaseModel):
    """Result of regenerating a single SOW section."""

    section_name: str
    content: str = Field(default="", description="New section content")
    needs_socratic: bool = False
    socratic_reason: str = ""
    socratic_probe: SocraticProbeOut | None = Field(
        default=None,
        description="New probe if the section still needs Socratic questioning",
    )


# ---------------------------------------------------------------------------
# Step event — frontend sends each field as the user fills it in
# ---------------------------------------------------------------------------


class StepEventRequest(BaseModel):
    """One step of the ADR creation flow.

    The frontend POSTs this after each field is completed.  The backend
    forwards it to the ADR_Agent and returns any suggestions.
    """

    step_name: str = Field(
        ..., description="MADR field name (e.g. 'context', 'options_considered')"
    )
    step_value: Any = Field(..., description="The value the user entered")
    partial_fields: dict[str, Any] = Field(
        default_factory=dict,
        description="All fields collected so far (partial AdrFields)",
    )
    project_dir: str = Field(
        default="",
        description="Project root — backend reads prior ADRs from .sdlicit/artifacts/adr/",
    )
    clarifications: list[ClarificationItem] = Field(
        default_factory=list,
        description="Prior Socratic Q&A; sent back when resuming an interrupted call",
    )


class StepSuggestion(BaseModel):
    """The main per-field suggestion returned by the ADR agent (BAML-extracted)."""

    agent_name: str
    field: str = ""
    message: str
    severity: str = ""  # low | medium | high
    references: list[str] = Field(default_factory=list)  # RAG doc refs (future)


class SupersedesHint(BaseModel):
    """Hint that the new ADR likely supersedes an existing one."""

    adr_id: str = Field(..., description="Filename stem of the existing ADR")
    adr_title: str = Field(..., description="Title of the existing ADR")
    reason: str = Field(
        default="", description="Brief explanation of why we think it supersedes"
    )


class StepEventResponse(BaseModel):
    """Structured response from a single step event.

    Fields are intentionally separate so the frontend can decide
    which parts to display and how.
    """

    suggestion: StepSuggestion | None = None  # primary ADR suggestion
    compliance: str | None = None  # Requirement-Agent notes
    artifact_meta: ArtifactMeta | None = Field(
        default=None,
        description="Populated on 'title' step — canonical filename for this ADR",
    )
    socratic_probe: SocraticProbeOut | None = Field(
        default=None,
        description="If present, the CLI must answer the probe and re-call",
    )
    supersedes_hint: SupersedesHint | None = Field(
        default=None,
        description="If present, this ADR likely supersedes an existing one",
    )
    # references omitted at top level — carried inside StepSuggestion for now


# ---------------------------------------------------------------------------
# Full-review — after all fields are complete
# ---------------------------------------------------------------------------


class AnalyseRequest(BaseModel):
    """Send the complete ADR or user input for analysis."""

    user_input: str
    context_files: list[str] = Field(
        default_factory=list,
        description="Existing ADR filenames for context",
    )
    project_dir: str = Field(
        default="",
        description="Project root — backend reads context files from disk",
    )


class AnalyseResponse(BaseModel):
    """Analysis result."""

    ok: bool = True
    suggestions: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Suggest ADR directions — ideation BEFORE picking a title
# ---------------------------------------------------------------------------


class ADRDirectionItem(BaseModel):
    """One suggested ADR topic the user should consider writing.

    The shape mirrors :class:`sdlicit.agents.base.ADRDirection` for
    transport. Carries WHAT decision must be made and WHY — never a
    proposed solution.
    """

    title: str = Field(
        ..., description="Proposed ADR title (a decision, not an answer)"
    )
    rationale: str = Field(..., description="Why this decision is needed now")
    priority: Literal["high", "medium", "low"] = "medium"
    gap_filled: str = Field(
        default="", description="Unresolved question/dependency closed"
    )


class SuggestDirectionsRequest(BaseModel):
    """Request for the ADR-direction ideation tool.

    The CLI / MCP caller is responsible for loading the brief and any
    downstream artifact text — the backend reads only ``project_dir``
    to discover prior ADRs (mirrors the ``/composing/step`` pattern).
    """

    brief: str = Field(..., description="Statement of Work / project brief content")
    project_dir: str = Field(
        default="",
        description="Project root — backend reads prior ADRs from .sdlicit/artifacts/adr/",
    )
    downstream_artifacts: str = Field(
        default="",
        description="Concatenated personas / user stories / Gherkin content (optional)",
    )
    uncovered_requirements: str = Field(
        default="",
        description="Comma-separated REQ-IDs not yet addressed by any ADR (optional)",
    )


class SuggestDirectionsResponse(BaseModel):
    """Ranked list of ADR topics the user should consider writing."""

    ok: bool = True
    summary: str = Field(default="", description="One-sentence coverage assessment")
    directions: list[ADRDirectionItem] = Field(default_factory=list)
