"""Pydantic models for the generation stage API."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, Field

from sdlicit.agents.transport import ClarificationItem, SocraticProbeOut

if TYPE_CHECKING:
    from sdlicit.helpers.artifact_naming import ArtifactMeta

__all__ = ["ClarificationItem", "SocraticProbeOut"]


# ---------------------------------------------------------------------------
# Personas
# ---------------------------------------------------------------------------


class Persona(BaseModel):
    """A user persona generated by the BDD Facilitator."""

    name: str
    role: str
    goals: list[str] = Field(default_factory=list)
    frustrations: list[str] = Field(default_factory=list)


class GeneratePersonasRequest(BaseModel):
    """Request persona generation from project artifacts.

    The backend reads ADR files from project_dir — no file data over HTTP.
    """

    project_dir: str = Field(
        ..., description="Project root — backend reads ADRs from disk"
    )
    srs_content: str = Field(
        default="", description="SRS document content (when available)"
    )
    prior_reviews: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Agent review outputs from the expansion stage",
    )
    clarifications: list[ClarificationItem] = Field(
        default_factory=list,
        description="Prior Socratic Q&A; sent back when resuming an interrupted call",
    )


class GeneratePersonasResponse(BaseModel):
    """Generated personas for user validation."""

    personas: list[Persona] = Field(default_factory=list)
    raw_suggestion: str = Field(
        default="", description="Raw agent output for debugging"
    )
    artifact_meta: "ArtifactMeta | None" = Field(
        default=None,
        description="Canonical filename and path — frontends must use this for saving",
    )
    socratic_probe: SocraticProbeOut | None = Field(default=None)


class GenerateGherkinRequest(BaseModel):
    """Request Gherkin generation from validated personas."""

    project_dir: str = Field(
        ..., description="Project root — backend reads ADRs from disk"
    )
    personas: list[Persona] = Field(default_factory=list)
    requirements: str = Field(
        default="", description="Requirements / acceptance criteria text"
    )
    clarifications: list[ClarificationItem] = Field(default_factory=list)


class GenerateGherkinResponse(BaseModel):
    """Generated Gherkin feature content."""

    gherkin: str = Field(default="", description="Gherkin feature file content")
    raw_suggestion: str = Field(default="")
    artifact_meta: "ArtifactMeta | None" = Field(
        default=None,
        description="Canonical filename and path — frontends must use this for saving",
    )
    socratic_probe: SocraticProbeOut | None = Field(default=None)


class UserStory(BaseModel):
    """A single generated user story."""

    story_id: str = Field(default="")
    persona_id: str = Field(default="")
    requirement_ids: list[str] = Field(default_factory=list)
    statement: str = Field(default="")


class GenerateStoriesRequest(BaseModel):
    """Request user story generation."""

    project_dir: str = Field(
        ..., description="Project root — backend reads ADRs from disk"
    )
    personas: str = Field(default="[]", description="JSON list of personas with ids")
    requirements: str = Field(
        default="[]", description="JSON list of requirements with ids"
    )
    clarifications: list[ClarificationItem] = Field(default_factory=list)


class GenerateStoriesResponse(BaseModel):
    """Generated user stories."""

    stories: list[UserStory] = Field(default_factory=list)
    raw_suggestion: str = Field(default="")
    artifact_meta: "ArtifactMeta | None" = Field(
        default=None,
        description="Canonical filename and path — frontends must use this for saving",
    )
    socratic_probe: SocraticProbeOut | None = Field(default=None)


# ---------------------------------------------------------------------------
# SRS (Software Requirements Specification) — generated from a SOW
# ---------------------------------------------------------------------------


class Requirement(BaseModel):
    """A single structured requirement."""

    req_id: str = Field(default="")
    category: str = Field(default="functional", description="'functional' or 'non_functional'")
    domain: str = Field(default="")
    statement: str = Field(default="")
    rationale: str = Field(default="")
    acceptance_criteria: str = Field(default="")
    kb_grounded: bool | None = Field(default=None, description="Whether this requirement is grounded in the KB")
    kb_ungrounded_claims: list[str] = Field(default_factory=list)


class GenerateSRSRequest(BaseModel):
    """Request SRS generation from a SOW."""

    project_dir: str = Field(..., description="Project root")
    sow_content: str = Field(
        default="",
        description="SOW markdown — when empty, backend reads latest SOW from artifacts/",
    )
    clarifications: list[ClarificationItem] = Field(default_factory=list)


class GenerateSRSResponse(BaseModel):
    """Generated SRS — both structured and rendered."""

    introduction: str = Field(default="", description="SRS introduction text")
    scope: str = Field(default="", description="SRS scope text")
    requirements: list[Requirement] = Field(default_factory=list)
    srs_markdown: str = Field(default="")
    raw_suggestion: str = Field(default="")
    artifact_meta: "ArtifactMeta | None" = Field(
        default=None,
        description="Canonical filename and path — frontends must use this for saving",
    )
    socratic_probe: SocraticProbeOut | None = Field(default=None)


# ---------------------------------------------------------------------------
# Cross-cutting Socratic consultation — REST mirror of the MCP tool
# ---------------------------------------------------------------------------


class ConsultSocraticRequest(BaseModel):
    """Free-form Socratic probe request (used by the guided flow)."""

    originating_agent: str
    what_was_asked: str
    what_is_known: str
    suspect_output: str = ""
    issue: Literal["ambiguous_input", "ungrounded_output"] = "ambiguous_input"
    clarifications: list[ClarificationItem] = Field(default_factory=list)


class ConsultSocraticResponse(BaseModel):
    """Either a probe or a stop signal."""

    status: Literal["probe", "skipped", "disabled"] = "skipped"
    probe: SocraticProbeOut | None = None


# ---------------------------------------------------------------------------
# Deferred model rebuild — resolve forward-referenced ArtifactMeta for Pydantic
# ---------------------------------------------------------------------------
from sdlicit.helpers.artifact_naming import ArtifactMeta  # noqa: E402

GeneratePersonasResponse.model_rebuild()
GenerateGherkinResponse.model_rebuild()
GenerateStoriesResponse.model_rebuild()
GenerateSRSResponse.model_rebuild()
